# Generated by Django 3.2.4 on 2021-06-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('memo', models.CharField(max_length=50, verbose_name='メモ')),
            ],
        ),
    ]
